### ISSUE TITLE
undefined method `authenticate!' for #<RailsJwtAuth::SessionsController:0x000000012ec68f98>

### ISSUE THREAD

**Issue by JonnalagaddaDevi** [rjurado01/rails_jwt_auth#113]
Add the below statement in sessions contoller, profiles controller (in whichever controller authentication is required)

      include AuthenticableHelper

While doing sign out, it checks authentication, at that time missed including authenticable helper

and In the documentation you have given the following URL for reset password

  url: host/passwords/:token

but it must be

 url: host/reset_passwords/:token

**Comment by rjurado01** [comment]
Thanks, I have updated README.

I will check the `include` when I have a time.

**Comment by rjurado01** [comment]
Fixed on v2.0.3
