### ISSUE TITLE
Error when executing: rails g rails_jwt_auth:install

### ISSUE THREAD

**Issue by Duleja** [rjurado01/rails_jwt_auth#118]
Hi! I just wanted to try this gem with fresh Rails 6 app but I encountered an error while executing the install generator command.

ruby 3.0.1p64
Rails 6.1.3.2

I generated my new Rails app with these options (options part is probably not importat):

`rails new 'name-of-the-app' --api --skip-action-mailbox --skip-action-text --skip-active-storage -T`

After this I added 'rails_jwt_auth' gem to a Gemfile:

`gem 'rails_jwt_auth', '~> 2.0', '>= 2.0.2'`

but I encountered an error when executing the install command from the documentation:

`rails g rails_jwt_auth:install`

This is the error I was getting:

/home/my-user-name/.rvm/gems/ruby-3.0.1/gems/rails_jwt_auth-2.0.2/lib/rails_jwt_auth.rb:30:in `<module:RailsJwtAuth>': undefined method `days' for 7:Integer (NoMethodError)

I found this: https://github.com/rails/rails/issues/40794

And I was able to fix the issue by requiring 'active_support/core_ext/integer/time' inside a gem

I uploaded a screenshot so you can see better what I am talking about.
![fix](https://user-images.githubusercontent.com/16133242/123245049-c18ff080-d4e4-11eb-98e9-640165a339c5.png)

After adding this line you can see on the screenshot I was able to run:

`rails g rails_jwt_auth:install`

Now, maybe this is not the best way to approach this issue but I was able to execute the install command after requiring this module.

Regards,
Dusan

**Comment by rjurado01** [comment]
Fixed on v2.0.3

**Comment by rjurado01** [comment]
Fixed on v2.0.3
