### ISSUE TITLE
Autogenerated initializer error

### ISSUE THREAD

**Issue by cfacello** [rjurado01/rails_jwt_auth#28]
Hi, there is a small error in the autogenerated initializer after installing the gem:

```
# number of simultaneously sessions for an user
# config.simultaneously_sessions = 2
```

should be

```
# number of simultaneously sessions for an user
# config.simultaneous_sessions = 2  
```

Thank you for this amazing job!

EDIT: 
The same is happening with 
`config.accept_invitation_url = 'http://frontend.com/accept_invitation'`

should be:
`config.invitation_url = 'http://frontend.com/accept_invitation'`

**Comment by rjurado01** [comment]
Solved. Thanks for your help.
