### ISSUE TITLE
No destroy action for RailsJwtAuth::RegistrationsController

### ISSUE THREAD

**Issue by carlinoo** [rjurado01/rails_jwt_auth#32]
I think I have done everything properly. The same "/registration" POST (for creating a new user) works perfectly fine. On the source code it seems like the method destroy is not written. Is it supposed to be written? Cause I could give it a try and add it myself :) BTW, this gem is awesome, its soo handy and beautifully written. Keep it up!

`{
    "status": 404,
    "error": "Not Found",
    "exception": "#<AbstractController::ActionNotFound: The action 'destroy' could not be found for RailsJwtAuth::RegistrationsController>",
    "traces": {
        "Application Trace": [],
        "Framework Trace": [
            {
                "id": 0,
                "trace": "actionpack (5.1.6) lib/abstract_controller/base.rb:119:in `process'"
            },
            {
                "id": 1,
                "trace": "actionpack (5.1.6) lib/action_controller/metal.rb:189:in `dispatch'"
            },
            {
                "id": 2,
                "trace": "actionpack (5.1.6) lib/action_controller/metal.rb:253:in `dispatch'"
            },
            {
                "id": 3,
                "trace": "actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'"
            },
            {
                "id": 4,
                "trace": "actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:31:in `serve'"
            },
            {
                "id": 5,
                "trace": "actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'"
            },
            {
                "id": 6,
                "trace": "actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `each'"
            },
            {
                "id": 7,
                "trace": "actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `serve'"
            },
            {
                "id": 8,
                "trace": "actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in `call'"
            },
            {
                "id": 9,
                "trace": "rack (2.0.5) lib/rack/etag.rb:25:in `call'"
            },
            {
                "id": 10,
                "trace": "rack (2.0.5) lib/rack/conditional_get.rb:38:in `call'"
            },
            {
                "id": 11,
                "trace": "rack (2.0.5) lib/rack/head.rb:12:in `call'"
            },
            {
                "id": 12,
                "trace": "activerecord (5.1.6) lib/active_record/migration.rb:556:in `call'"
            },
            {
                "id": 13,
                "trace": "warden (1.2.7) lib/warden/manager.rb:36:in `block in call'"
            },
            {
                "id": 14,
                "trace": "warden (1.2.7) lib/warden/manager.rb:35:in `catch'"
            },
            {
                "id": 15,
                "trace": "warden (1.2.7) lib/warden/manager.rb:35:in `call'"
            },
            {
                "id": 16,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'"
            },
            {
                "id": 17,
                "trace": "activesupport (5.1.6) lib/active_support/callbacks.rb:97:in `run_callbacks'"
            },
            {
                "id": 18,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:24:in `call'"
            },
            {
                "id": 19,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'"
            },
            {
                "id": 20,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'"
            },
            {
                "id": 21,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"
            },
            {
                "id": 22,
                "trace": "railties (5.1.6) lib/rails/rack/logger.rb:36:in `call_app'"
            },
            {
                "id": 23,
                "trace": "railties (5.1.6) lib/rails/rack/logger.rb:24:in `block in call'"
            },
            {
                "id": 24,
                "trace": "activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `block in tagged'"
            },
            {
                "id": 25,
                "trace": "activesupport (5.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'"
            },
            {
                "id": 26,
                "trace": "activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `tagged'"
            },
            {
                "id": 27,
                "trace": "railties (5.1.6) lib/rails/rack/logger.rb:24:in `call'"
            },
            {
                "id": 28,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'"
            },
            {
                "id": 29,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/request_id.rb:25:in `call'"
            },
            {
                "id": 30,
                "trace": "rack (2.0.5) lib/rack/runtime.rb:22:in `call'"
            },
            {
                "id": 31,
                "trace": "activesupport (5.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'"
            },
            {
                "id": 32,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'"
            },
            {
                "id": 33,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/static.rb:125:in `call'"
            },
            {
                "id": 34,
                "trace": "rack (2.0.5) lib/rack/sendfile.rb:111:in `call'"
            },
            {
                "id": 35,
                "trace": "rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'"
            },
            {
                "id": 36,
                "trace": "railties (5.1.6) lib/rails/engine.rb:522:in `call'"
            },
            {
                "id": 37,
                "trace": "puma (3.11.4) lib/puma/configuration.rb:225:in `call'"
            },
            {
                "id": 38,
                "trace": "puma (3.11.4) lib/puma/server.rb:632:in `handle_request'"
            },
            {
                "id": 39,
                "trace": "puma (3.11.4) lib/puma/server.rb:446:in `process_client'"
            },
            {
                "id": 40,
                "trace": "puma (3.11.4) lib/puma/server.rb:306:in `block in run'"
            },
            {
                "id": 41,
                "trace": "puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'"
            }
        ],
        "Full Trace": [
            {
                "id": 0,
                "trace": "actionpack (5.1.6) lib/abstract_controller/base.rb:119:in `process'"
            },
            {
                "id": 1,
                "trace": "actionpack (5.1.6) lib/action_controller/metal.rb:189:in `dispatch'"
            },
            {
                "id": 2,
                "trace": "actionpack (5.1.6) lib/action_controller/metal.rb:253:in `dispatch'"
            },
            {
                "id": 3,
                "trace": "actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'"
            },
            {
                "id": 4,
                "trace": "actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:31:in `serve'"
            },
            {
                "id": 5,
                "trace": "actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'"
            },
            {
                "id": 6,
                "trace": "actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `each'"
            },
            {
                "id": 7,
                "trace": "actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `serve'"
            },
            {
                "id": 8,
                "trace": "actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in `call'"
            },
            {
                "id": 9,
                "trace": "rack (2.0.5) lib/rack/etag.rb:25:in `call'"
            },
            {
                "id": 10,
                "trace": "rack (2.0.5) lib/rack/conditional_get.rb:38:in `call'"
            },
            {
                "id": 11,
                "trace": "rack (2.0.5) lib/rack/head.rb:12:in `call'"
            },
            {
                "id": 12,
                "trace": "activerecord (5.1.6) lib/active_record/migration.rb:556:in `call'"
            },
            {
                "id": 13,
                "trace": "warden (1.2.7) lib/warden/manager.rb:36:in `block in call'"
            },
            {
                "id": 14,
                "trace": "warden (1.2.7) lib/warden/manager.rb:35:in `catch'"
            },
            {
                "id": 15,
                "trace": "warden (1.2.7) lib/warden/manager.rb:35:in `call'"
            },
            {
                "id": 16,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'"
            },
            {
                "id": 17,
                "trace": "activesupport (5.1.6) lib/active_support/callbacks.rb:97:in `run_callbacks'"
            },
            {
                "id": 18,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:24:in `call'"
            },
            {
                "id": 19,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'"
            },
            {
                "id": 20,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'"
            },
            {
                "id": 21,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"
            },
            {
                "id": 22,
                "trace": "railties (5.1.6) lib/rails/rack/logger.rb:36:in `call_app'"
            },
            {
                "id": 23,
                "trace": "railties (5.1.6) lib/rails/rack/logger.rb:24:in `block in call'"
            },
            {
                "id": 24,
                "trace": "activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `block in tagged'"
            },
            {
                "id": 25,
                "trace": "activesupport (5.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'"
            },
            {
                "id": 26,
                "trace": "activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `tagged'"
            },
            {
                "id": 27,
                "trace": "railties (5.1.6) lib/rails/rack/logger.rb:24:in `call'"
            },
            {
                "id": 28,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'"
            },
            {
                "id": 29,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/request_id.rb:25:in `call'"
            },
            {
                "id": 30,
                "trace": "rack (2.0.5) lib/rack/runtime.rb:22:in `call'"
            },
            {
                "id": 31,
                "trace": "activesupport (5.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'"
            },
            {
                "id": 32,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'"
            },
            {
                "id": 33,
                "trace": "actionpack (5.1.6) lib/action_dispatch/middleware/static.rb:125:in `call'"
            },
            {
                "id": 34,
                "trace": "rack (2.0.5) lib/rack/sendfile.rb:111:in `call'"
            },
            {
                "id": 35,
                "trace": "rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'"
            },
            {
                "id": 36,
                "trace": "railties (5.1.6) lib/rails/engine.rb:522:in `call'"
            },
            {
                "id": 37,
                "trace": "puma (3.11.4) lib/puma/configuration.rb:225:in `call'"
            },
            {
                "id": 38,
                "trace": "puma (3.11.4) lib/puma/server.rb:632:in `handle_request'"
            },
            {
                "id": 39,
                "trace": "puma (3.11.4) lib/puma/server.rb:446:in `process_client'"
            },
            {
                "id": 40,
                "trace": "puma (3.11.4) lib/puma/server.rb:306:in `block in run'"
            },
            {
                "id": 41,
                "trace": "puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'"
            }
        ]
    }
}`

**Comment by rjurado01** [comment]
Destroy action is not implemented because this is a critical point that it must be protected correctly.

Each project has its own user destroy policy so you must implement it. For this, you can overwrite RegistrationsController as explained in [this section](https://github.com/rjurado01/rails_jwt_auth#custom-controllers) and add destroy action.

Thanks for your support.
