### ISSUE TITLE
signed_in? and current_user are useless

### ISSUE THREAD

**Issue by carlinoo** [rjurado01/rails_jwt_auth#45]
Hi, "signed_in?" is obviously false if you don't set the authenticate!. But if you do the authenticate! and the user is not logged in, the execution of the program will stop.

I need a way to see if a user is signed_in?, and show them something. If they are not signed_in? I want to show them something else in the same controller and action.

Kind regards,

Carlino

**Comment by carlinoo** [comment]
Cool, well you are doing an amazing work. I use this every day and it is just perfect. When I learn how to make gems, I will start contributing too!!

**Comment by rjurado01** [comment]
Great !!

**Comment by rjurado01** [comment]
Added `authenticate` helper in `v1.3.0` cd2904440542147075ada74a3bd59e8088e0a917
