### ISSUE TITLE
Why confirmation method is GET instead of POST or PUT/PATCH?

### ISSUE THREAD

**Issue by jgalisteo** [rjurado01/rails_jwt_auth#5]
It has no sense to me.

I think that GET should only be used for retrieving information.

**Comment by rjurado01** [comment]
It is copied from devise that uses it to redirect after confirm but is is true that in API workflow this has not sense.

**Comment by rjurado01** [comment]
Updated to PUT: ef65aefb42f31cae63acbe42cd36eefef1a55968
