### ISSUE TITLE
Run before_action on all actions except sign in/sign up

### ISSUE THREAD

**Issue by veeral-patel** [rjurado01/rails_jwt_auth#61]
Thank you for this gem! My `application_controller.rb` currently looks like this:

```
class ApplicationController < ActionController::API
    include RailsJwtAuth::AuthenticableHelper

    before_action :authenticate!
end
```

I'd like to ensure every action is authenticated, so I'd prefer to put `before_action :authenticate!` into `ApplicationController` instead of into every controller separately.

However, if I do this, then when I make a POST request to `/session` (in order to acquire a JWT token), I get a `RailsJwtAuth::NotAuthorized` exception.

How can I whitelist some of the actions from `rails_jwt_auth` to prevent this?

**Comment by rjurado01** [comment]
This is a Rails use case: try this: https://stackoverflow.com/a/36302983/1827284

**Comment by veeral-patel** [comment]
@rjurado01 Thanks! So what you're saying is that I need to add something like:

```
skip_before_action :authenticate_user!, only: [:create]
```

To my `SessionsController` (provided by `rails_jwt_auth`), right?

Where would I find this file? Or should I override it somehow?

**Comment by rjurado01** [comment]
Yes, you need to overwrite the `SessionsController` like:

```ruby
# app/controllers/sessions_controller.rb
class RegistrationsController < RailsJwtAuth::RegistrationsController
  skip_before_action :authenticate_user!
end
```

And add it to your `config/routes.rb`:

```
route resources :session, controller: 'sessions', only: [:create, :destroy]
```

You can skip also from `destroy` as this methods calls authenticate! [source](https://github.com/rjurado01/rails_jwt_auth/blob/master/app/controllers/rails_jwt_auth/sessions_controller.rb#L23)

**Comment by veeral-patel** [comment]
Sorry is it:

```
class SessionsController < RailsJwtAuth::SessionsController
  skip_before_action :authenticate_user!
end
```

or 

```
class SessionsController < RailsJwtAuth::SessionsController
  skip_before_action :authenticate!
end
```

**Comment by rjurado01** [comment]
Second option, I have updated my comment.

Please, don't close the issue before each new comment and reopen it again. Use the "comment" option instead of "close and comment".

**Comment by veeral-patel** [comment]
@rjurado01 got it, thank you! And my apologies, I kept clicking the "Close and comment" button instead of the "Comment" button for some reason.
