### ISSUE TITLE
Little confused about DELETE /sessions/:id route (and other DELETE routes for that matter)

### ISSUE THREAD

**Issue by ckhall** [rjurado01/rails_jwt_auth#64]
So the route is defined, from the generator, as:

`DELETE /session/:id(.:format)`

However, the documentation in the readme simply shows setting the auth header and there is no mention of setting the `:id` param in the path.

> Delete session
{
  url: host/session,
  method: DELETE,
  headers: { 'Authorization': 'Bearer auth_token'}
}

Not passing an `:id` results in a route not found error.  Passing in ANY value for `:id` gets me past the route error, however, the value of the param does not appear to be used anywhere.

Can you explain why the param is necessary at all?  Why is it not mentioned in the documentation?

Thanks.

**Comment by ckhall** [comment]
So it seems using `resource` vs `resources` in the routes.rb file fixes this issue.  Seems the generator should do this, yes?

**Comment by rjurado01** [comment]
I will check It.

**Comment by rjurado01** [comment]
Yes you are right. I have fixed it and registration route: https://github.com/rjurado01/rails_jwt_auth/pull/65
I will publish new release with this change.

Thanks.

**Comment by rjurado01** [comment]
Published [v1.4.1 release](https://rubygems.org/gems/rails_jwt_auth/versions/1.4.1)
