### ISSUE TITLE
Create user without password?

### ISSUE THREAD

**Issue by bradherman** [rjurado01/rails_jwt_auth#78]
Do you have any suggestions for handling the case where we'd like to create users in our database (for something like progressive signup) without a password?  Devise allowed you to bypass password verification, but looking at the code here it seems like that's not an easy option.

Thanks!

**Comment by rjurado01** [comment]
You can't but you can set provisional password, which is how `Invitable` module works:

* You register a user only with auth field value (ex: {email: 'user@email.com'})
* Invitable module set provisional password: [code](https://github.com/rjurado01/rails_jwt_auth/blob/master/app/models/concerns/rails_jwt_auth/invitable.rb#L66)
* Email is send with invitation token: [code](https://github.com/rjurado01/rails_jwt_auth/blob/master/app/mailers/rails_jwt_auth/mailer.rb#L53)
* Using invitation token user can set new password [code](https://github.com/rjurado01/rails_jwt_auth/blob/master/app/controllers/rails_jwt_auth/invitations_controller.rb#L16)

Another option could be try to remove `password presence validation` using `after_validation hook`. This validation is added by [has_secure_password](https://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html) method.
