### ISSUE TITLE
Confirmation link sent by email using get and no put in the url

### ISSUE THREAD

**Issue by Ronair** [rjurado01/rails_jwt_auth#79]
When I register a new user and send an e-mail for confirmation, when I click on the link the message "No route matches [GET]" / confirmation "" appears, I saw that in the past action: show was used, but it was changed to: update ( : put).

As the link is generated by rails_jwt_auth I don't know how I could send a [PUT] "/ confirmation".

May help to solve this problem.
Thank you.

*** LOCAL GEMS ***
rails_jwt_auth (1.5.0)
    Author: rjurado
    Homepage: https://github.com/rjurado01/rails_jwt_auth
    Rails jwt authentication.

**Comment by rjurado01** [comment]
You can see this in the documentation: [link](https://github.com/rjurado01/rails_jwt_auth#confirmation). I have updated it since it was wrong. Sorry for the issue.

**Comment by Ronair** [comment]
I upgraded to version 1.6.0.

When I click on the link in the email it gets and not put.

Using the postman returned 204, but when I click on the email sent "Confirm my account" it still has an error No route matches [GET] "/ confirmations"

OK
comand postman: curl -X PUT  http://e647fb06.ngrok.io/confirmations/bgHw7s6enwycEEJ2mcRKopC3 

ERROR
link e-mail: http://e647fb06.ngrok.io/confirmations?confirmation_token=bgHw7s6enwycEEJ2mcRKopC3

**Comment by rjurado01** [comment]
The email link is a GET to your web page addind token as parameter.
Once the user is on your website, you must get token from url and make the PUT.
If all is Ok you can show a message to the user.

**Comment by rjurado01** [comment]
![Untitled Diagram (1)](https://user-images.githubusercontent.com/1703608/75098943-4c44a080-55bc-11ea-8ede-8851bef4ca0d.png)

**Comment by Ronair** [comment]
I understood how I should work.

I thought I was wrong because I was working differently. I have an android app that creates the user in a rails app (api json). When an email is sent I thought I should just confirm it by the link because I didn't have a view in the rails api app. I will create the web part so you can receive the get and fire the put as the image.
Thank you.
