### ISSUE TITLE
Receiving 'invalid' response when trying to update password

### ISSUE THREAD

**Issue by navimaia** [rjurado01/rails_jwt_auth#89]
I'm trying to update my user's password from my front-end, and I am receiving an 'invalid' error message, which is coming from here:
https://github.com/rjurado01/rails_jwt_auth/blob/master/app/models/concerns/rails_jwt_auth/authenticatable.rb#L46

I am using a custom controller, based on the docs. This is what is returning the 'invalid' message:

```
      current_user.update_with_password(
        update_params.merge(auth_tokens: [jwt_payload['auth_token']])
      )
```

It is the correct password, so I'm not sure what is happening. It is trying to call an `authenticate(current_password)` method, but I can't even find that definition in the codebase. 

Am I missing something?

**Comment by rjurado01** [comment]
This error happens when you send invalid password into `current_password` field.

**Comment by navimaia** [comment]
I understand, but I am sending the correct password. I have triple checked the API request and the user on the console and dev logs. 

Can you tell me where that authenticate definition is? I can’t find it in the repo ... there is only a controller authenticate action.

**Comment by rjurado01** [comment]
This method is defined by `has_secure_password`: [doc](https://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html)

You can try using rails console with: `User.find(id).authenticate(password)`
