### ISSUE TITLE
Sending wrong confirmation code

### ISSUE THREAD

**Issue by navimaia** [rjurado01/rails_jwt_auth#90]
Hello,

I am experiencing an issue where the gem is sending the incorrect confirmation_token.

If I try to update a users email, I get sent a confirmation link, however, that confirmation link is incorrect, and the confirmation_token is referring to the LAST confirmation_token on the User, not the newly generated one, and therefore confirmations do not work.

I believe the fix to this would be to add:
`return false unless save`

to here:
https://github.com/rjurado01/rails_jwt_auth/blob/master/app/models/concerns/rails_jwt_auth/confirmable.rb#L35

Like you did here:
https://github.com/rjurado01/rails_jwt_auth/blob/master/app/models/concerns/rails_jwt_auth/confirmable.rb#L59

**Comment by rjurado01** [comment]
The code seems fine, this is a `before_update` hook so model must be valid.

Which steps have you made to reproduce the issue?

**Comment by navimaia** [comment]
I create a new User with an email and password.

The system then sends me an email to confirm my email.

The `confirmation_token` sent in this email, properly matches the `confirmation_token` set on the user: `ed1N84bzGfHyDGdmrk6cz1mV`.

```
#<User:0x00007fc51fc78c60
 id: "dc1c74ef-a641-4401-bae2-fc297a0683cd",
 email: "first@example.com",
 created_at: Tue, 05 May 2020 10:30:22 EDT -04:00,
 updated_at: Tue, 05 May 2020 10:30:22 EDT -04:00,
 password_digest: "[FILTERED]",
 auth_tokens: [],
 unconfirmed_email: nil,
 confirmation_token: "ed1N84bzGfHyDGdmrk6cz1mV",
 confirmation_sent_at: Tue, 05 May 2020 10:30:22 EDT -04:00,
 confirmed_at: nil,
 reset_password_token: nil,
 reset_password_sent_at: nil,
 last_sign_in_ip: nil,
 last_sign_in_at: nil,
 invitation_token: nil,
 invitation_sent_at: nil,
 invitation_accepted_at: nil,
 invitation_created_at: nil>
```

Everything seems like it's working fine.

The user then confirms their email, and everything works:

```
#<User:0x00007fc51fc78c60
 id: "dc1c74ef-a641-4401-bae2-fc297a0683cd",
 email: "first@example.com",
 created_at: Tue, 05 May 2020 10:30:22 EDT -04:00,
 updated_at: Tue, 05 May 2020 10:33:14 EDT -04:00,
 password_digest: "[FILTERED]",
 auth_tokens: [],
 unconfirmed_email: nil,
 confirmation_token: nil,
 confirmation_sent_at: Tue, 05 May 2020 10:30:22 EDT -04:00,
 confirmed_at: Tue, 05 May 2020 10:33:14 EDT -04:00,
 reset_password_token: nil,
 reset_password_sent_at: nil,
 last_sign_in_ip: nil,
 last_sign_in_at: nil,
 invitation_token: nil,
 invitation_sent_at: nil,
 invitation_accepted_at: nil,
 invitation_created_at: nil>
 ```

 Now, if I try to update the users email after the account is created, I receive an email with an empty `confirmation_token`, even though it is set on the User record:

 ```
 #<User:0x00007fc51fc78c60
 id: "dc1c74ef-a641-4401-bae2-fc297a0683cd",
 email: "first@example.com",
 created_at: Tue, 05 May 2020 10:30:22 EDT -04:00,
 updated_at: Tue, 05 May 2020 10:35:40 EDT -04:00,
 password_digest: "[FILTERED]",
 auth_tokens: ["2J2kjksYrSSWQxwPvadkf77K"],
 unconfirmed_email: "first1@example.com",
 confirmation_token: "JFLumqmJ93KBUHu79gpnt936",
 confirmation_sent_at: Tue, 05 May 2020 10:35:40 EDT -04:00,
 confirmed_at: Tue, 05 May 2020 10:33:14 EDT -04:00,
 reset_password_token: nil,
 reset_password_sent_at: nil,
 last_sign_in_ip: "127.0.0.1",
 last_sign_in_at: Tue, 05 May 2020 10:35:40 EDT -04:00,
 invitation_token: nil,
 invitation_sent_at: nil,
 invitation_accepted_at: nil,
 invitation_created_at: nil>
 ```

Becaue the token is empty in the email sent to the user, the user cannot update their email, so they return to the form and try to update it again. This time the email sent contains the "last" `confirmation_token` of `JFLumqmJ93KBUHu79gpnt936`, but the new User record contains a different confirmation code - `95bJe7HtX2JWW7xK2H6YpeNE`:

```
#<User:0x00007fc51fc78c60
 id: "dc1c74ef-a641-4401-bae2-fc297a0683cd",
 email: "first@example.com",
 created_at: Tue, 05 May 2020 10:30:22 EDT -04:00,
 updated_at: Tue, 05 May 2020 10:38:55 EDT -04:00,
 password_digest: "[FILTERED]",
 auth_tokens: ["2J2kjksYrSSWQxwPvadkf77K"],
 unconfirmed_email: "first2@example.com",
 confirmation_token: "95bJe7HtX2JWW7xK2H6YpeNE",
 confirmation_sent_at: Tue, 05 May 2020 10:38:55 EDT -04:00,
 confirmed_at: Tue, 05 May 2020 10:33:14 EDT -04:00,
 reset_password_token: nil,
 reset_password_sent_at: nil,
 last_sign_in_ip: "127.0.0.1",
 last_sign_in_at: Tue, 05 May 2020 10:38:55 EDT -04:00,
 invitation_token: nil,
 invitation_sent_at: nil,
 invitation_accepted_at: nil,
 invitation_created_at: nil>
 ```

 Because these codes never match up (it always sends the email with the old confirmation_token before updating the user record), the user can never confirm their account if they update their email.

 This happens every time I have tested this. It always works the first time, but never once after updating the user email.

**Comment by rjurado01** [comment]
I'll check

**Comment by navimaia** [comment]
Yes, I have `send_email_changed_notification` set to false. I am only referring to the confirmation email that is sent.

It properly sets the token the first time, and I can confirm the email, like I described above, but after the account has accepted the invite, and another request is made by the user to edit their email, no token is present in the email sent to the user.

Because no token is present on this request, the front-end form errors. So a natural reaction by the user would be to go and try to update their email again from the front-end form. When they do this, a token gets sent, but it is an incorrect token, sending a stale token before a new one gets updated.

The steps to reproduce are triggering a request to edit the users email, then send a second request to edit the email, and you'll see the token is incorrect.

The form I'm referring to is a user profile form on my web client that allows a user to update their email, and hits an endpoint on my API that is basically the same as this one you have in the readme:

```
class CurrentUserController < ApplicationController
  before_action 'authenticate!'

  def update
    if update_params[:password]
      # update password and remove other sessions tokens
      current_user.update_with_password(
        update_params.merge(auth_tokens: [jwt_payload['auth_token']])
      )
    else
      current_user.update_attributes(update_params)
    end
  end

  private

  def update_params
    params.require(:user).permit(:email, :current_password, :password)
  end
end
```

I can create a video tomorrow.

**Comment by rjurado01** [comment]
Have you actived `deliver_later` option ?

**Comment by navimaia** [comment]
Yes, I use deliver later.

**Comment by rjurado01** [comment]
Check new version [v1.7.0](https://github.com/rjurado01/rails_jwt_auth/releases/tag/v1.7.0)

**Comment by navimaia** [comment]
Hello, 

The issue still persists. I also changed to `config.deliver_later = false`, but the same issue appears.

Here is a confirmed user, `henry@example.com`:

<img width="374" alt="Screen Shot 2020-06-19 at 9 46 06 AM" src="https://user-images.githubusercontent.com/62469315/85139340-467d6580-b212-11ea-8be0-758d3d72f267.png">

When I update the email to `henry1@example.com`, I get sent an email with a token:

<img width="240" alt="Screen Shot 2020-06-19 at 9 47 14 AM" src="https://user-images.githubusercontent.com/62469315/85139350-4b421980-b212-11ea-9b11-21b572b83f48.png">

which matches what it says in the console:

<img width="439" alt="Screen Shot 2020-06-19 at 9 47 28 AM" src="https://user-images.githubusercontent.com/62469315/85139388-57c67200-b212-11ea-8c72-2d7b460286e5.png">

I then confirm the change in the email sent, and it all works fine. Here is the user at this point. I do notice that the `confirmation_sent_at` is not set back to `nil`:

<img width="451" alt="Screen Shot 2020-06-19 at 9 47 52 AM" src="https://user-images.githubusercontent.com/62469315/85139451-70cf2300-b212-11ea-84cd-d8aae5a770a5.png">

I then update the email again to `henry2@example.com`, but this time, no token is sent:

<img width="143" alt="Screen Shot 2020-06-19 at 9 48 16 AM" src="https://user-images.githubusercontent.com/62469315/85139516-88a6a700-b212-11ea-9795-da3b4040f316.png">

but there is a `confirmation_token` on the user:
 
<img width="429" alt="Screen Shot 2020-06-19 at 9 48 31 AM" src="https://user-images.githubusercontent.com/62469315/85139561-99efb380-b212-11ea-9821-49ec5ada7e6e.png">

I looked at the email template and it's calling `@user.confirmation_token`. The email is pulling the proper user and displaying the proper content for the user, just the incorrect confirmation_token. Since it's blank, it seems that it's sending the email before having the confirmation_token updated in the database.

I then go and update the email again, to `henry3@example.com`, and am sent a new email. It now is showing the outdated confirmation code from the previous request:

<img width="277" alt="Screen Shot 2020-06-19 at 9 49 02 AM" src="https://user-images.githubusercontent.com/62469315/85140152-de7b4f00-b212-11ea-88e9-e25d140b9d61.png">

and if I look in my console, the confirmation_token has been updated, but the email sent the outdated token:

<img width="430" alt="Screen Shot 2020-06-19 at 9 49 14 AM" src="https://user-images.githubusercontent.com/62469315/85140230-fa7ef080-b212-11ea-923e-012531368604.png">

So the issue persists, and it's sending outdated codes, so the email is going out before the database is being updated. This happens no matter `deliver_later` or `deliver_now` and happens every time I've tested.

**Comment by rjurado01** [comment]
Sorry, I missed some code on version 1.7.0.

Error must be fixed on versión: [1.7.1](https://github.com/rjurado01/rails_jwt_auth/releases/tag/v1.7.1)

**Comment by navimaia** [comment]
The changes you implemented seemed to have fixed the issue with the email I was having above, but introduced a new issue.

The new issue is that once I confirm the change by clicking the link in the email (which works), a second email immediately gets sent out with a blank token. If we can prevent this second email from sending out after clicking the link, the issue should be fixed.

**Comment by rjurado01** [comment]
Fixed on version: [1.7.2](https://github.com/rjurado01/rails_jwt_auth/releases/tag/v1.7.2)

**Comment by navimaia** [comment]
This changed fixed it. Thank you for hard work with this issue.

**Comment by rjurado01** [comment]
Thank you for your information.
