### ISSUE TITLE
Undefined method render_204 and render_422

### ISSUE THREAD

**Issue by bradherman** [rjurado01/rails_jwt_auth#97]
In my app, when using the gem, I get 500 errors any time the code tries to call the render_204 and render_422 methods

**Comment by rjurado01** [comment]
If you want to uses this helpers in yours controllers you have to add this code to `app/controller/application_controller.rb`:

```ruby
class ApplicationController < ActionController::Base
  include RailsJwtAuth::RenderHelper
  ...
end
```

**Comment by bradherman** [comment]
This isn't in my own controllers, it's the gem erroring.

**Comment by rjurado01** [comment]
I need more info, Which action are you making? Can you add some logs?

**Comment by bradherman** [comment]
I feel like an idiot now... Someone had written an undocumented monkey patch to modify the render_session payload and accidentally overwrote the whole module.  Thanks for looking and sorry for wasting your time!

**Comment by rjurado01** [comment]
Don't worry

**Comment by JulesDebeaumont** [comment]
Hello, same issue with the render_204 method.

Rails version : Rails 7.0.2
Rails Jwt Auth version : 2.0.3
Action : RailsJwtAuth::ResetPasswordsController#create

> NameError (undefined local variable or method `render_204' for #<RailsJwtAuth::ResetPasswordsController:0x0000000000ef10>
> Did you mean?  render):
> 
> rails_jwt_auth (2.0.3) app/controllers/rails_jwt_auth/reset_passwords_controller.rb:30:in `create'
> actionpack (7.0.2.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
> actionpack (7.0.2.3) lib/abstract_controller/base.rb:214:in `process_action'
> actionpack (7.0.2.3) lib/action_controller/metal/rendering.rb:53:in `process_action'
> actionpack (7.0.2.3) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
> activesupport (7.0.2.3) lib/active_support/callbacks.rb:107:in `run_callbacks'
> actionpack (7.0.2.3) lib/abstract_controller/callbacks.rb:233:in `process_action'
> actionpack (7.0.2.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
> actionpack (7.0.2.3) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
> activesupport (7.0.2.3) lib/active_support/notifications.rb:206:in `block in instrument'
> activesupport (7.0.2.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
> activesupport (7.0.2.3) lib/active_support/notifications.rb:206:in `instrument'
> actionpack (7.0.2.3) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
> actionpack (7.0.2.3) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
> activerecord (7.0.2.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
> actionpack (7.0.2.3) lib/abstract_controller/base.rb:151:in `process'
> actionpack (7.0.2.3) lib/action_controller/metal.rb:188:in `dispatch'
> actionpack (7.0.2.3) lib/action_controller/metal.rb:251:in `dispatch'
> actionpack (7.0.2.3) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
> actionpack (7.0.2.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
> actionpack (7.0.2.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'
> actionpack (7.0.2.3) lib/action_dispatch/journey/router.rb:32:in `each'
> actionpack (7.0.2.3) lib/action_dispatch/journey/router.rb:32:in `serve'
> actionpack (7.0.2.3) lib/action_dispatch/routing/route_set.rb:850:in `call'
> rack (2.2.3) lib/rack/etag.rb:27:in `call'
> rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
> rack (2.2.3) lib/rack/head.rb:12:in `call'
> activerecord (7.0.2.3) lib/active_record/migration.rb:603:in `call'
> actionpack (7.0.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
> activesupport (7.0.2.3) lib/active_support/callbacks.rb:99:in `run_callbacks'
> actionpack (7.0.2.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
> actionpack (7.0.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
> actionpack (7.0.2.3) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
> actionpack (7.0.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
> actionpack (7.0.2.3) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
> railties (7.0.2.3) lib/rails/rack/logger.rb:36:in `call_app'
> railties (7.0.2.3) lib/rails/rack/logger.rb:25:in `block in call'
> activesupport (7.0.2.3) lib/active_support/tagged_logging.rb:99:in `block in tagged'
> activesupport (7.0.2.3) lib/active_support/tagged_logging.rb:37:in `tagged'
> activesupport (7.0.2.3) lib/active_support/tagged_logging.rb:99:in `tagged'
> railties (7.0.2.3) lib/rails/rack/logger.rb:25:in `call'
> actionpack (7.0.2.3) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
> request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
> actionpack (7.0.2.3) lib/action_dispatch/middleware/request_id.rb:26:in `call'
> rack (2.2.3) lib/rack/runtime.rb:22:in `call'
> activesupport (7.0.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
> actionpack (7.0.2.3) lib/action_dispatch/middleware/server_timing.rb:20:in `call'
> actionpack (7.0.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
> actionpack (7.0.2.3) lib/action_dispatch/middleware/static.rb:23:in `call'
> rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
> actionpack (7.0.2.3) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
> rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
> railties (7.0.2.3) lib/rails/engine.rb:530:in `call'
> puma (5.6.2) lib/puma/configuration.rb:252:in `call'
> puma (5.6.2) lib/puma/request.rb:77:in `block in handle_request'
> puma (5.6.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
> puma (5.6.2) lib/puma/request.rb:76:in `handle_request'
> puma (5.6.2) lib/puma/server.rb:441:in `process_client'
> puma (5.6.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'`
